---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app snapshot-controller
  namespace: flux-system
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/part-of: &namespace kube-system
spec:
  dependsOn:
    - name: flux-system
      namespace: flux-system
    - name: snapshot-crds
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/namespace: *namespace
  interval: 4h
  path: ./kubernetes/apps/snapshot-controller/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
  wait: false
