apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: renovate
type: Opaque
stringData:
  RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:K/2ypPdGynpp2POM2NWo9jInsCNZuxgBKBuIorcoNrXDY+Dl0lMD2A==,iv:lNUrdEAR1KYNkh+YNokca3IuwE7x49CsSBy4Zgi002U=,tag:qX6vpXquzw0SDf64q7T4iA==,type:str]
  RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:1K9te6Y=,iv:++GzPkvEbJTteNFSEKR15nJdOzfScbLOMqZnY6NHgyQ=,tag:S7uE3R1XCIINlmZvlT742A==,type:str]
  RENOVATE_ENDPOINT: ENC[AES256_GCM,data:H7UA4aRGDSep/47sgMtpv6nbG4Unwg==,iv:WFnuSa8xx1HNlHadFymBOABaJYMWNMT+omNKChducno=,tag:4tcQvTt6QqwHPcCJEMhIFg==,type:str]
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:ARLV+6SzeyHQFkvBNRkm0RZRv2fXEg+iaNfA6Q/StMmf9WhwlF1lg9UBN4ew9uJcz4C+Y0Na1pPssScxgJF1,iv:opHlqX+GQDJiFId0HDNewA24q/cmgC6hV5JZycsvQz0=,tag:hg1Fnw03b7vfRaD6oVdThA==,type:str]
  RENOVATE_PLATFORM: ENC[AES256_GCM,data:1yV9pv1W,iv:sogkmBnBBCyabdVBAVRCyXKKVwgLULbLyKsvfClyJpE=,tag:2hk7Nx7iwXtyj8HRmCOoxw==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:/MzaIeMRfvLwQjPl93O2V5Wgbuy5sbXWp1eKHkbFOHDolN6GfJvMoA==,iv:tpP2AHkrK0T15hmfN14el+BR2Q1LNRvnutTYLnoqo4s=,tag:uAfJJF435Ou5qPhq4tv2+A==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacDkrcUJrQnkyVklkVmht
        c0RraWhDVGVMK1UxL1R3VXluUGhzYVprb0RzCk4veHpQN0FSRXZzRC9CbUxBaGcz
        bHQ2Z1NWN0gwbkZOc2xLRStsZWJFelEKLS0tIHVKQ0JXUnJGamVWQ3VSTGloL09Z
        QUpqbENnQTMyMnJUdFNYcUNYWVkyc3MKDl+Kfo5cCMhyMzaS/pp9GQqMi+9fdhdJ
        DvL8B9eQHfV/TmwYWMkJeq/qqlH+unqQowUxxzrtnrh9GD2pvpKaHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T20:56:46Z"
  mac: ENC[AES256_GCM,data:BUitIiYZrsBzx4Db+qmvzQ/RYvnOMJq677BOcqk2kMOqlIHkZdiawf98yPXWi5DzXQz34WReDuzuxGS9BMlsS8j+FRp4NE/louDqfgNI6U28vJgK6CmV+MFP3upuGMCNYuvUEQlZC1Ev32AEZ41UnNQepdW2N015A4spBwAZI1c=,iv:eRUFtNM9n4U+FoCcSxx+iFXKsszgnCWN7WHoQ0tKLU0=,tag:DzpDiw23EAwvfsSti2gykQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
