apiVersion: v1
stringData:
  LD_SUPERUSER_NAME: ENC[AES256_GCM,data:GdMza0AXfyvzso0=,iv:lHq98s1bphaKFjujYQVEiVp9iEfL2nDfe6bfzdn80AQ=,tag:Mdv1FoY+PJLPsbMR9mcbmw==,type:str]
  LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:VudD4DILMWYcXyqUrPOBZKY7xfV0aY2ZYHV9dIr6Bko=,iv:4kJHS8mBlFjKFtt9x1wCyS7yh2SXttvJ4kvbBIk36O4=,tag:O1tgYI+4aVSUOfXZgTPxNw==,type:str]
kind: Secret
metadata:
  name: linkding-config
  namespace: linkding
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZUhENFVhbzNucmwwTWln
        STQ1TXV1QmxJMGs0bnRFK1dQS3NkZjVYbTMwCmVWaHdDL3gvRkNIU01jWUFqUE5P
        UmZoWnNwZDF4WFMrVmpiQlZsODlwc1UKLS0tIGRjY3ZFeGtyZmwvcE94dlk2UFIx
        aDZNR0RRaTVyUlhBRDMrMEx1OHBIazAKZoktnalwf0L/mIWIoqwYO8GINZKoE8Ko
        mMsLLm9JSt1HzJO8jObzffqOPwnGWZh5ogESs8Rm+eTaIMueuOgY7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T19:23:56Z"
  mac: ENC[AES256_GCM,data:P+skig8rjcoYqY69LvY9y93sIm2W3BAv3R6Mm0PwJQZqIovb6Fq9+7whRYySBHiKKEI8hTTC5YZ3CcAPaOijUm6Kh1PrvXi0NIID56vAeAnJQfvwhtBAARz8Z8arvEAsHCfuM8sZ2pRrZvkPKUrM4q4BV6EvIvrmg2Oa4cOfDuk=,iv:gxkrSiS+UzP9GIWRFvkIuwMHYK0bRytVn+SWrPOSCSg=,tag:rmHlbcUykvdAUGNapuDgXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
