---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dndwiki-bookstack
  namespace: dndwiki
spec:
  hostnames: ["dndwiki.${SECRET_DOMAIN}"]
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: dndwiki-bookstack
          namespace: dndwiki
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /
