apiVersion: v1
kind: Secret
metadata:
  name: dndwiki
  namespace: dndwiki
stringData:
  rootUser: ENC[AES256_GCM,data:ApuA7Dq90L2GP1a6GdGEuvM=,iv:94RRPQ17XjFCzdic0otK0/AOUdtAv8am/YEgGXrqyts=,tag:zjbMywG7O5DdoBbh6hfcSg==,type:str]
  rootHost: ENC[AES256_GCM,data:Xg==,iv:fTTyznMl7VANHp8Z8OFB2jGOiWsI59BW4mW+jpEjq8E=,tag:2qodtbE+o6F/g60855i9kA==,type:str]
  rootPassword: ENC[AES256_GCM,data:MGG1FFGpMZNKeMDgDFBdc0Pthg3Qjx6mXBcEnHFSIuk=,iv:QeeVvYVBuT5Z/twRbPjQEyRhKFr+zTiMNiQwnFSPpm0=,tag:7tX7uDXTyNCOfiPuCrnIcQ==,type:str]
  appKey: ENC[AES256_GCM,data:ND3xFPrDsg/d+D3SNPuFFKbEg09o5j23JX3QM5x3VmI=,iv:6MXhlIcaBypJd4PgS1a1bFBLFtE2j3mwW3Z6ZsTMjrA=,tag:ZqwMLtEofN24i8qUNIi30Q==,type:str]
  appUrl: ENC[AES256_GCM,data:X2wNJXy7Fo0PrvCfDqd6PInKvU7s6QYV,iv:iAfl+17DBUv+N3M5+dbnFR6OPqa/t6+TWYbfv1Zxduo=,tag:N5RrT0Suj+etDtkHO6HlGQ==,type:str]
  mailFrom: ENC[AES256_GCM,data:KrfhBjfaGm7zdRIahtkyhg==,iv:qqNH3B6NUm3cvumTH+MFQbgUzOblkihXrbsArdpYiho=,tag:GOthuEo0dZzUq+6Nk7SyPQ==,type:str]
  mailFromName: ENC[AES256_GCM,data:gIZJbgDzsLTMCu77gYmVTwI=,iv:T4Mpil4iTovAkHUgbWjhaI85RKaDyCjZFi6oj6AxDOc=,tag:uBUTL06eMkXAfesJ5E781g==,type:str]
  mailHost: ENC[AES256_GCM,data:7WC4+Mq+gXg84rQRqM/yWQ==,iv:AHymWwRQ4Gu+rmxvlZ0LokZ493j7y+3REYUiOQrUGE0=,tag:f+JgYPtVicummKOapiXCXw==,type:str]
  mailPort: ENC[AES256_GCM,data:3BHB,iv:wULyQkmLAg7MHC4eLj3717TTUAvcllvbTn5ivDKxwiw=,tag:FLqunpxwppsrgpacPgTdxw==,type:str]
  mailUsername: ENC[AES256_GCM,data:NWeHSD6poA==,iv:LKqYLRoZNGq9lew5irt4F5pxA3tRZIcK10v8PguJZBw=,tag:iJCCLuyy5vKmIrsW5/NC1A==,type:str]
  mailPassword: ENC[AES256_GCM,data:+ead6wf1oMdyqbTSBBPerQ==,iv:DyvbpafjGwtK5O5pHOnnrGkUywPkGEsVs6VsJ9I0VdA=,tag:qTBszB83GN4bi2waZgcOEw==,type:str]
  mailVerifySsl: ENC[AES256_GCM,data:Ajqfnw==,iv:81+nukJKc//WP+TyJErjvQRHdWbnf1Y3W9vzevgMEFs=,tag:B2Au71UgrtPykKUDEfwCqg==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTjBHRW9BYW8wZmdpYlJl
        dDBXQjRHc1NrNThDTlQxNHdhNGNlR2U3bFJVCmphTFNJZzJZWE01bHl0dVg1NFI1
        UHd6VXlJV1dNLzBmVEYyRXIycysyUWcKLS0tIGt6Vi9TNTNRNThmZm1VaW5GTzB3
        NHpKR2VUOXFYNk1jY3FJWGN5em5KZlUKCMR301SXsZJa5qm7bVim4rdYOyCQS7dP
        y316nMXeyXKhGtY8FERiesJvN3iu4bhJ952WPX6ocXhdK4RUO05HYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T19:26:17Z"
  mac: ENC[AES256_GCM,data:Yaih0RbcE8tycW2u9DIAbXgIdmnSpVo60c3rXXjzvxmqIKBJ7Led9FOJv8wb6PDQsUfp4PUUdfDTiaR/YfDZs07yvg2BQ3VxLgTZ3/i7aPV85HTp9AU/04VemV2ABB9FY55Q1CpmZo/jf4iyk4BHBEeuZ58pVTmT4AUAVwOfOOM=,iv:w2PRn9jHpMtr3GdEgewvuafdmj+PFoKuKUXfQJLux10=,tag:pCvCxSaf+mQF6OBNyNtpNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
