apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:NRbWAQvD2cGQYzdoCO/l83Tzt1yPp2gR22b/Fl5SMNpGyHpmzj9ebw==,iv:VylE3pIHu/iBcPI+Bhzptp4r1U8Lfh/2P52BNunojlE=,tag:QlEcM26MOMLQgtsDql9w6g==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCenlBWHRMTldWcFhhMUdF
        dmdrbjhMUldHbEM1eTE4SzRVMHpFSDA3ejN3Cm9raUxiZlo2bkRyTnEzdmxpcUN2
        ditOODBDUjhzNkJ6ZW5tYVNSLy9xWlkKLS0tIEd0NzRSa1F5RHdSM2tXQzlvVkV5
        MzZITVFKajYwRVpOclFBSEJQSDBZK00KtEIbiBb+8e0Z7T5syFWVimXlipegHk7k
        stdtq4PWRUj1Rb5CK7Y7KfT91lVwBkHNKAjM23UiLdyDlFBUV1ADgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T17:25:09Z"
  mac: ENC[AES256_GCM,data:p/c8suIGMCmdSHvOkBlAxAVFdV3WM/F1Vw+msMGE+rDaVU0PZC1gc2liyuBZpKDDYclqE1cUVjjUd3QgY0rXMgu+NZuqYnV48qk3fIk1b2EHdZLg7HlwBdunzfBfIuutunNUIfHaOMUXHmctfrjE9qArFVi0p9qMQIjVheW4iC8=,iv:mSrGbE7RiYG0KVYKeCtqFrmOfj+/C88Yphonm2vlshk=,tag:4/OekRCttUcNoUWWSWKJRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
