apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:5vBQMvQI9DmpheyOwI4xWjtpA17KMgFjzGr3QChwLeqTvnpsslqqng==,iv:vM1STENYKmUVaLOMOTQ+0i6FXtwACOjVcIF+4de6ngw=,tag:y5fF/JCLNsl0t2rD+Spg+Q==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K3dyVWQ1MzRlNXJjOFMx
        cHVzRVcwb28ySjBzcGRMN2d0dm5VYUR6aVVJCk5vVElZRC9LVm1vR044S1BZenN6
        YVZYWmhYM2w4NTVCdktmSjZ2eU9xQXcKLS0tIG16dmxveldCKzNlb1lENDUrNDlQ
        MEYwQUdPOHZmaGZHaUZ0R05UeHIxOG8KHuT0IeVKgArqynygkufe8xEJN8X8iFXx
        ipLjSQEgE00t1vbJWPtnAB2+tiMtH0xGydwR/1RsMkcE0Jwh9ftHXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T17:11:45Z"
  mac: ENC[AES256_GCM,data:kpwUOUf3ylI+L1TVFQD33n/zSD1FSl8Xg1TuXXDmxX3vl2+a/APdf6LpIP6Bg4+vyuVBN54SAbXJ4KFIlLy22s9wjG2DHB0jzQsXC/plQjrLT2R9HNOogoM9MLis0Yq/JJb1RLtlDPjIrAkrH7QIRcbWU5EiiC/Z3diinJr/LnA=,iv:BuFl2Yij7+pUxUEuNUNFwgP1u+O647zgeJOST/DCvFY=,tag:IpVW7zLFLdItMKEY+EDtHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
