apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SJj1MUXMYUY=,iv:Ap8jbROZwVzgdX8BUdL6CeB4v3DRwODOBDJNxdc5X+Q=,tag:Keh8XvVJmIro5qRpGMxKjg==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZUhtWEV1RzVHamZEZTlT
        QTNVSGVkNkxMVlMyRmVZSEpINTd0SDF3SlhZCitOZkRkcWtGeE00TFpMVjBHTDJH
        VHoxNUxYcEVqQld4eGYvWDBoWjdjcWcKLS0tIHFVU0cyang0SDI2MEdYRUliejdz
        U3dFSE5iMWFsRmtHQTZFdjE0Zm9UTTAKGMPquXD0NJKlubMn6ECJT0N3fEzGL31T
        FBDfJfsHHvMw3fjdhDglHQg2lWsz1kOe3Kzpxfw/CQFcdlbYZwYw+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T17:25:09Z"
  mac: ENC[AES256_GCM,data:Fe3WtjKFROZi+AZwQmkrbu6cuDakox+nlI40M7ubXyb+xmc378jQIi2E9FgVWNlSeMLzlcza5RVmKKPk3cizitAbhRzxWjk6kY2p7iEKvynljZ82W5Z+K/RxbAULsus3qnWA6wVK9efvr1t7qv2l+yWxh5OJvf5bYAHWGUR0pMU=,iv:nwRswpCqaD7mG8300Edr3QUx/wb8ihV220YOkf5xvSo=,tag:0NaxUtrQjJe2KFb2j4odVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
