apiVersion: v1
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:gzabTVaG1rQ=,iv:naIBuC6nSU/yQTR2cYKxfmSX/nfuLNpzHU26Mdszues=,tag:u2OAVPUeyYtYz60MUdPzcA==,type:str]
  SECRET_DNS: ENC[AES256_GCM,data:yrSdw46LVL9ZMEE=,iv:8lY+FLXlmc1wAGGxb/qLcvwWsbjRra6z/zar/+E8lWs=,tag:ZDLI8x8YFAquxV2w48hbpA==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSHdQZmdzVGVGdi82dWk3
        MUhEYUFkZFk0a2VHMmlyT1NJRWhiMEdjMkg0Ckl0cnVwbGFqNytyZ2YxR1hVU3Q1
        cVIvdDlMbm9uRXBvaTRmL1RpWFd0Z3cKLS0tIFBURFJwUm1xdnlzamRPTjdnbzBu
        ODNBdzdveG9tQ00ydlBnSW8wUy9PdDgKh3GaJScikpnD7OmJGUXs20x4SphAaMXX
        X6wX3qE7M0EOL01bTU8067Z1GXQ0GCFt41r9jMoazNBWDOB5tJRrDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T04:12:42Z"
  mac: ENC[AES256_GCM,data:tnCV8YRV1gKlioYmnx+CtRX9bpc2GxogLwvVTzT0h6i9Az2Ouc6hgpGb/gnN4tVIuyJT8T9Ebly7UmcmWZWxjMgVDZTSiPcNPNVdhwME4lFeT3liFAZ6sl38AvBPQz2G4xYXv82aPwGFpo+SbtarzHaJPxUa7pc6+PxCb5c0bvI=,iv:PPVxMMKwPBrk8c/1ROaHgmNFFCoWX5/DAsk9B8f1CdI=,tag:keu3xi61Yu8RJEJDg0Y52A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
