apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+yx57fFJEtU=,iv:EMGX2os5XY40OmhO3uUP6i0MZ+9H1qJGnwfrQZFmGWc=,tag:i9DYuRRPyKiJmHLSVTr5Ig==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZmo4MHdjZy85bXVSOXUy
        bkd4cUZaejl0RldVU2w2V0lQQUhFV0ZUVkUwCjNEN0hXSVg0dWJJWWRYLy8xazNQ
        NTZRVWRoNVJObExtejF1ZFJvc2h3dzAKLS0tIDNNTXM4MzBaR0RQaVlPYk9Td0hr
        cWlvbk4wSkk4QzU3OGdtZ2E5V1BIWmcK0J42/ZWP/3c63jufqvKzNAAaV1crhNxE
        E7GPD2VdaruMUecBm116jbrI18EUE/JOGcr7mMhKFQvZh1ROoE488A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T17:11:45Z"
  mac: ENC[AES256_GCM,data:A8eIJfdXECNd/CJ/yF9i11o4WALwAPJxLENn9snRZ8ID0vv06d2Q95dsQjQL76GPn6W5pUlYmZy/G45xvKCDHq08ysM2MxB8qE9sb8wSD50NpuCSTN1ZrXFLvpFqpTqekSdMgIzOwIBgDz5rNLPat80TCSw/L1+wOn/ESjLzuR0=,iv:9scuAOsL1O5Mh+aJSVS1bq1KwR1BuZ0wVHhS0zYCCyg=,tag:og5ug4fUzx1OvoUo+rG2FQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
