apiVersion: v1
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kiMGOdd7FWo=,iv:BQ1uJ+cPy4+SxZ4HjTAEEnmqGb6NDwnKOMfSM0M2dqY=,tag:din1vv5uHd/HRhojEgoctg==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodmtZOWo4T0R2enMwR0xU
        aDljRGtHelhaRldSNHNHRFlGVDFBK0xXMjFVCndrVDdsaStoWnM1U2RranMwc1VL
        OEg4a09aanM3Rm8wKzlQalRhMlBpUm8KLS0tIHlBcEZNMGlibHZwWWM2RGhrTnVq
        M0d0YnJ5RnpwNGVBZjRmTEdMTlFPTncKIGbnQuDy4RQpE8s7walUYyzMPMtObEvR
        tRQ5nsBjTRt8YjhiLbzfEKMEyLOGNeg7cfgrmVaG6iHqc6NsOVm3Kg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T18:50:29Z"
  mac: ENC[AES256_GCM,data:9Za/Ph+O6w+wcYsaLkg1xyULFkWZ6low2GFPquPTXG9hU1URonGpwJa8ZkXcynp7Xg1v9L/e/xPGWy5A38kpXdVLglnGxTtnL8Pr5jgx2TWKB/cgd8TM4NfWiJgNXkEEY2QMOUg4cgAlThIb9F55ZFoDHFLPwOsrhDM2Mxu48rU=,iv:erOaV0+Gw+usZtxZ+z89KMezqqv+WTyZ4pmUxWfsYeY=,tag:cYGmGWQ4Enx39Kfnvkadlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
