apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ie7rhxsFTAAGYWBbMT/rYRF3eQjSHx6QXhwMx70ws9A=,iv:A/SN8wWOnznWsEs0BzzkCu/crjvBMXi2MaYGinkoG/A=,tag:ubyUgdFJaYdIr1dqHDEglw==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWk1PSHZScmNzaHJNMllS
        NXJ4Q1hja3J5SkdmT01zYzZkcFpzTzF4OWhVCncya09TZGRwbWVuNWlhdU5PZVdQ
        WFRQZHZncWMvNmtZL1FheE1LcDBSS1UKLS0tIHJlbmFSMExvOVJwZlQ3aG1IYmk0
        Q1NpVGcvamdOS0NYOTdvbmZjeGF6em8KwdFPpjsFD5G7v3Xogug823dpuRXwqIgk
        Ji6C1xgGK6OLwIEGpzgwIGArvfITWLmiKTjA8svswoHovJgeQrdTNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T06:44:36Z"
  mac: ENC[AES256_GCM,data:xGjAxy5tWS2nI2ttZPLRVODaRHu+8qG2v/jq6zHvcJu8N4N/KwXUjNFGs2u/IQWby61X2Jp6gaYqmMMnlznnkDIwxI7o8M/4rE0IwMT5WbMwq+HceezgS0GqaFd34o5gB9PrDTiQDCJYdNpEYgfLvnxWO1h/UY3RgVvO9e1QNrE=,iv:9FIbElW2rg88Se3X3rdR3RFg2qxPrmm5AfipFBhOVSY=,tag:v5BLMhHPox3PZK7nghy+VQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
stringData:
  address: ENC[AES256_GCM,data:5zpp7GxcEgns3uj/2OvK2Nm66em8Wcf1WdmlWWog5lYgqqMXondGIb2JDEmLrGhIILLOfdPPrV8OVldOK5tgwF2VrYgT09JwcxmXfKGMbOQMMOau6uLsSWJN54HbBq0l4QyiYHI+3dtg/Fi3hrpJn9La7ZyWO9a5gg==,iv:X9mcd8PHr+ufkpc2VhQzvg1IE7qspMpOP+PoSfMXjR4=,tag:FjiGqOBXd7bP2OIGRzl9eQ==,type:str]
kind: Secret
metadata:
  name: discord-webhook
  namespace: flux-system
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWk1PSHZScmNzaHJNMllS
        NXJ4Q1hja3J5SkdmT01zYzZkcFpzTzF4OWhVCncya09TZGRwbWVuNWlhdU5PZVdQ
        WFRQZHZncWMvNmtZL1FheE1LcDBSS1UKLS0tIHJlbmFSMExvOVJwZlQ3aG1IYmk0
        Q1NpVGcvamdOS0NYOTdvbmZjeGF6em8KwdFPpjsFD5G7v3Xogug823dpuRXwqIgk
        Ji6C1xgGK6OLwIEGpzgwIGArvfITWLmiKTjA8svswoHovJgeQrdTNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T06:44:36Z"
  mac: ENC[AES256_GCM,data:xGjAxy5tWS2nI2ttZPLRVODaRHu+8qG2v/jq6zHvcJu8N4N/KwXUjNFGs2u/IQWby61X2Jp6gaYqmMMnlznnkDIwxI7o8M/4rE0IwMT5WbMwq+HceezgS0GqaFd34o5gB9PrDTiQDCJYdNpEYgfLvnxWO1h/UY3RgVvO9e1QNrE=,iv:9FIbElW2rg88Se3X3rdR3RFg2qxPrmm5AfipFBhOVSY=,tag:v5BLMhHPox3PZK7nghy+VQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
stringData:
  address: ENC[AES256_GCM,data:d/ec/8ntfyEZ8KaN9gWA+VjzoO4jGQYmbYnvoUn7ZAGbvVMIw7x/KRsCyja+/rSF+bY4zkMw5xpcxj4tzE7w8F3JA9RGdExDrY/HLoNaa1Ifn4ppUcsgjLBnUcnhG2jdvJhTKKyeA0H+arxqZI6JVeRnd2V3hmPWLyTSOdMoN6hxfEqVP0ra5J2YaX+zkg==,iv:zHmfCmYkeXp64UrWvsct2tV+JKL0BkfapBbkTr+DcbQ=,tag:E26vKR9KecJUTU7OUnWIPw==,type:str]
kind: Secret
metadata:
  name: pushover-webhook
  namespace: flux-system
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWk1PSHZScmNzaHJNMllS
        NXJ4Q1hja3J5SkdmT01zYzZkcFpzTzF4OWhVCncya09TZGRwbWVuNWlhdU5PZVdQ
        WFRQZHZncWMvNmtZL1FheE1LcDBSS1UKLS0tIHJlbmFSMExvOVJwZlQ3aG1IYmk0
        Q1NpVGcvamdOS0NYOTdvbmZjeGF6em8KwdFPpjsFD5G7v3Xogug823dpuRXwqIgk
        Ji6C1xgGK6OLwIEGpzgwIGArvfITWLmiKTjA8svswoHovJgeQrdTNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T06:44:36Z"
  mac: ENC[AES256_GCM,data:xGjAxy5tWS2nI2ttZPLRVODaRHu+8qG2v/jq6zHvcJu8N4N/KwXUjNFGs2u/IQWby61X2Jp6gaYqmMMnlznnkDIwxI7o8M/4rE0IwMT5WbMwq+HceezgS0GqaFd34o5gB9PrDTiQDCJYdNpEYgfLvnxWO1h/UY3RgVvO9e1QNrE=,iv:9FIbElW2rg88Se3X3rdR3RFg2qxPrmm5AfipFBhOVSY=,tag:v5BLMhHPox3PZK7nghy+VQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
