apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:eg2+ZXLzOa9O/aNoW+PTO2lTPa04+YjSpO3jAvmPXvk=,iv:C9JucIWT4dx3fmXIglnxFX845NehpyO9q7su1ETzL1c=,tag:HVeIyU2jY+1bBjIniRzufw==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZEFmSWo2QVZVb2lINnZX
        by9YQTVqblBLakRFUDFSK1d1WEVoUGxaN0VzCllvM2hBUlBxZkltU0ZuZktDMXE2
        cDZYanZXNFNOZ0hwSGRsVERiMEF0YVEKLS0tIGFPS1N5ckZzUll5aEM1VDFSY3pw
        eU9HVlAxbzBua2ZsRUFweHQycHB3SG8K5MIDvnNwwgKEeTt8o6MdUF4NzxFZGf5r
        pqkDo+dkrarhh1jNNpEKlfC/NW2qZqyuKrGYdG/7Qp+eqRmalpSIfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T17:11:45Z"
  mac: ENC[AES256_GCM,data:L2AsYeLKlUF6PPKPSFG01s4UXD3gAWPcnMXsfl06g77Cn09Xo3pndLY53mk/wWAyjqdXwAuzjTP46QTjieeSOzo9Q7/hdMf6rRh8kTOkZu31bp8LP/Tj+AX8UE5PZO5tD9vv2dqbJex3d3eJCWuJ4CiePZ5eRcZkfgrNLMejwSg=,iv:M3WV2ah9CQg6nNv4wKjAKikje2R+HcKJgS8f+/RQUfY=,tag:dk4uAlHBiE/zVdn4NUXQsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
