---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-smb-media
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0555
    - file_mode=0555
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-mjolnir.${SECRET_DOMAIN}/media##
    volumeAttributes:
      source: //mjolnir.${SECRET_DOMAIN}/media
    nodeStageSecretRef:
      name: media-creds
      namespace: jellyfin
