apiVersion: v1
stringData:
  username: ENC[AES256_GCM,data:jTLh,iv:8egKE5nizn2YdoQCDzgcrbqpMKE3qlLt6yFNITdxmig=,tag:kaOd4ZDLO2meW0A+WG28Bw==,type:str]
  password: ENC[AES256_GCM,data:A69EldSLWeEOw92DFrZo2Ycp4IXKB+TgtxddBK9H,iv:97JJP3qEiWIaGwMlvanVgfBscOvF3gDOcOvEozevFkA=,tag:0L/9yY1gTCJVBJueQQ2a2w==,type:str]
kind: Secret
metadata:
  name: media-creds
  namespace: jellyfin
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmFDbnp6VUtLa1dQT2Nk
        ZEttMUdqNkxjVS9FZUVwSnBrNEtSZkIwWGhZCkw4ZnB3aW9CQVgva215UzhFRUZX
        Y0x2SnltN3gxdzNva1A1by9wbXY5cmcKLS0tIHQwYVJlQ3dNL1paSmJsSmJCc3BO
        M1BoK1ZNc3FkU04xb2xJc0ZwVmxhREkK67J2JIh/BzU5mSZZqQazCJNXQrFeD+hx
        o5wKfrNMA3KmGp/xNPIQaBqYEsreqpgw1UvjeC1+6AXGZNDYu/sK7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T03:21:31Z"
  mac: ENC[AES256_GCM,data:Nhf1LBKhRlQ5iwSAtfAeotS6ElcL6YHDfMb2ik0y4rYUpMnTUxVa4onDbyChmDlOWZGFuoB1Z90r9WCME0HyY9UAqfq7ZCF34Lr9G1CnsC3uh4XFMU/EaKsIOMGd5GmTwLosK40aHyFd2DT0U4H8Kx+21Xyt0Hj62ZOISef0Ngg=,iv:Yqxq3RmqM8+BgslGKR5iQkEWtT24fRUSdf+XcApmPJE=,tag:G5x2Xi8DHOg9tFc3njqv/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
