apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: prometheus
stringData:
  admin-user: ENC[AES256_GCM,data:xmoJV8xUB0cTMOc=,iv:qRzbs8SYq7oav3A6HG0NTpf1Gg3GChYoX/a7empRzRk=,tag:xKPxX6ZpRBVrBd8EpGdESQ==,type:str]
  admin-password: ENC[AES256_GCM,data:vsPhcNwhxRZ3Pg5AZsc45Q9mpaRsxDT2,iv:30fmqW2qm/vNopnR2zZaAfbWBZmdf8u2tszPLRxfOvA=,tag:+/5WJgCb7Ufr67RucypnSg==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN0FSMFQxeHdsNWphWlBJ
        TEJyblRra3RKTjhTcjVQVXpXL1NLRC9memtJCkJlTGZUclRRZzNocFgvN1hsalc3
        aWhucmhnNVk4cTQ5Nlg0ZE00dU50cDQKLS0tIE0rWkFFN1JYRkdzUjc1U0VBc1JH
        ckQ1TUR4cEg1Y3VCekd0ZWxsZi9kUHcKJe8ew/6FvwK8W9UmoPVsn3y6uySvV9MV
        llRKf13VX2k5FwYMTSF20DBY8hW0bHDy5vPsLxQ/vRbbIFlUfXCGsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T02:10:50Z"
  mac: ENC[AES256_GCM,data:aHKe2j88Ot0XI5JRD4Wi/MWuqbmgqED2WZvcm8Muiw+6Lv6wVlYEk1uC46dZKOX93ZIsAWHM2Ecd6Zx+YZssVI5L2/iAHHcLoiUkqfunWRzgKIQ9iTmcUxzGuDIKWe6wsHOEKsHsIs6cJayQ9uBKO65go8uqW06dIg+tdscny2U=,iv:cu7WQHXbSC2rQ3AxrwPNL6O+vMzCQhOkQVlFq3h7zPM=,tag:s897BjGggmOoOpxElRosHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: prometheus
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Noef2LOjg12LSABcFEIq7TauCYqmF1K0m/6HWAJJkLBVdTfo4R30BuaUomelbAAyUCqp96cFtc44RsT3j3SCjSoVc8Aps+SjT1nYedesU5n0abbL1bu3jnz7Icf3H9oJdFRtdHmxIv28tqP5nQaQjc/CFGQzSdFjsw==,iv:QyvZ64WV/aIy8V5ObfS8VqUEp8WKVM+G6NquLgHvCgc=,tag:WvC1KEbe4B59cyaz9DSIUw==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN0FSMFQxeHdsNWphWlBJ
        TEJyblRra3RKTjhTcjVQVXpXL1NLRC9memtJCkJlTGZUclRRZzNocFgvN1hsalc3
        aWhucmhnNVk4cTQ5Nlg0ZE00dU50cDQKLS0tIE0rWkFFN1JYRkdzUjc1U0VBc1JH
        ckQ1TUR4cEg1Y3VCekd0ZWxsZi9kUHcKJe8ew/6FvwK8W9UmoPVsn3y6uySvV9MV
        llRKf13VX2k5FwYMTSF20DBY8hW0bHDy5vPsLxQ/vRbbIFlUfXCGsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T02:10:50Z"
  mac: ENC[AES256_GCM,data:aHKe2j88Ot0XI5JRD4Wi/MWuqbmgqED2WZvcm8Muiw+6Lv6wVlYEk1uC46dZKOX93ZIsAWHM2Ecd6Zx+YZssVI5L2/iAHHcLoiUkqfunWRzgKIQ9iTmcUxzGuDIKWe6wsHOEKsHsIs6cJayQ9uBKO65go8uqW06dIg+tdscny2U=,iv:cu7WQHXbSC2rQ3AxrwPNL6O+vMzCQhOkQVlFq3h7zPM=,tag:s897BjGggmOoOpxElRosHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
