apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: prometheus
stringData:
  admin-user: ENC[AES256_GCM,data:h7PW4uov8uGRgHk=,iv:5Y34bbYzHgfn74QmNdfinOwNSDtFZ7jIgiF1OQcFvpc=,tag:dT6BF941bgKUpVj2+7UWEw==,type:str]
  admin-password: ENC[AES256_GCM,data:ElcIU+ixz1k+JHryKqMFZIcIzaHt7zzo,iv:wkGnkRHluxl2O430FGLU9priTaXwADyGPkWZykFIpkI=,tag:Cfl1luVIGx2ScGhGkZeFhQ==,type:str]
type: Opaque
sops:
  age:
    - recipient: age1kylkkmndtj8c8d4cxgkyetxqjmkuww4tsah0w4mzekrcqvw4cugqtgcpwg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUGlOTnZab2xPSndiRWh6
        cGdTYm9Sbytzaks5WnBIM2tsdTNOcER3Z240Cm1aV0dWWWp0WkhjS1QxSHpBSEsv
        OFdzeGpHdDRPQmxuWkdpVk5PQTdYWEUKLS0tIGlSZWxEbytLK0VHS2N1aFd5RjYz
        NzVhSDhQYjlUM2JGVFRVWW4yeXFuRlkKo50GZJIDS+TahNwc2IjWpsYWADlU9XEt
        VH5FSs5cU85m7tTofmVXEFp3MSbwbHj3pbN9FEQrtQC7HKttye7FBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-19T18:04:49Z"
  mac: ENC[AES256_GCM,data:rmaM7oxzchqpptq6KpIlFg0DJcd+0Jd1I4M9ZSf7YRp0bjZCxy7pUIdE6v/ChKLYO91suOmrhUawon8vdu8f1n5MWKv9IvIMd6DIamSI8Gy5pSZp6R4uSXHfHY1atz7A+hmbKlVpFpUpIBIoOL1wBkCIhhQIJK43S2s0RNxPjQw=,iv:mrK/nMq3UUMwzsTlmLfyMK6BY4bBHqWwR5wWpTWRPmk=,tag:ZWZvVYucs2EViVYs38PFUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
