apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: prometheus
stringData:
  admin-user: ENC[AES256_GCM,data:rWZLa6NTrbFMtHY=,iv:svTDbcShCXiICVyID8BHUiY3mmCEFHKvdYNstxWcC6k=,tag:HuOdwCYr4iTsEsnHyqLqeA==,type:str]
  admin-password: ENC[AES256_GCM,data:DJk7sYBhnINGIWqJK99oUPpPcX3c1sD3,iv:rWfB2JoZ96cHXPDBhj+ivUws3KVFmqQSTpXuuWK8x/I=,tag:z9g/NYX9VAkMHqAmaaguCA==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNG5zWjJINEgrTWllMERO
        aVg4a1pVY2tJM0RFenlpem52V1B4djZDeFdjCnRHNDZmSVpKbTFKeCtkZDNsbkdQ
        TU8zWE5HVmZMeTBIT0M5M1Ftb3FzNXMKLS0tIEp5RnBlNmZxOWVqT2Z1S25UUHp0
        dEtNdmFTeXZrUXV5bjlRNDRtN1k1eGcKSOa7s+jDeKgKGraD0j31ROmuQoko0NEO
        mJzVNrzPcTUWM6RLdDiZoM1UaeF5qzFm/5PQ/P2g4aHaNOjv2mYQAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T19:01:33Z"
  mac: ENC[AES256_GCM,data:ukxkw2TFQObA3WntfsAT/QsJU7e78Znj3DevnaSSXoisWFmIzSe0Z8meWaTlGCKYH1H+ONEOTtvfbX+XS2Id+IOq5/8Wf8BdHlel+nOEo1pJDb+arrKK97vvshFHEdGJAgY2h2zs/1sBkE8v/sd6jWYEF8lsZEYvFzbHWplG9EY=,iv:21/iF6iHgyN50kdlxydd6S6yE9c7/i78g96IOt1WRfM=,tag:BxC+TIBmK7bLN8+RNa+Swg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
