apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:jrust3q8KDgCJxHReTp83fXuvYXgenNOXnagdPOMmb3YYlViMCJzQrILDDSRJHqyfIAt6iSj3Qf7+APwl6LR/t0UCUVd3leM7gjpcajTQXFfTEhPk7VAw5YXtoNIS37znYMqsjZ6cvIkzOyyFZWi9UPOY9sxZH0xyoDKr06Lzne4WPKrhF6DuXBRmvRlsGbyPc2IXn410W360oP+gmSOmNDACZ2DGRUgK4xp7vpvu802y33L,iv:a+mHx9xjjNkkc6VM3KWJ+lT/P4nEoiG8aR41iDSHQlc=,tag:zRpZ595v7yESaMMOTtp8sA==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySjJSNit5YnlpVk96RWFN
        bmxNcVFQV0VvRGJ4QytZdXNVTE5HaFhpQ1NJCnRSUmxQTXhBVmVGdm9kR05aTkNK
        NDVFVmpqUlUvQzdyMHRSbW90UW9yWlUKLS0tIG1TcHFLeEVKRVF6R0ZRZ21xS1Rk
        Y21vOUlYSS9MbCtQOXFJZ1FUT05tUTgK/1OU8b5926f8umdtQo+1Qdx4H/DJm39P
        V7arxcdSYVCO1aRnpql24blB0NlQbGzPuhUyQmnQQfdaa3HnXwqgiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T17:25:09Z"
  mac: ENC[AES256_GCM,data:nPxbmRWAc5gq46slPe++0qBk4hcsuM/Va2fb5sySMI1uyw5Y9F7V+7sdG9j9n5kZUrejiyrgEjeRyaeqwpbn3KTh61pnLJjJwYR4vf8OdzhNsC+tVE7w3zDSnzy+5B5LvwXrrUCK/5viqgsgxbDzDlV6aiNnMn3zYQjAEO+Dooo=,iv:irdxgWvdLjuNAL7/y+oHdWkjBFxhFSzC0GTabrRJhjU=,tag:WHFVKI1IQOtGveU+HrdLmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
