apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-configuration
  namespace: homeassistant
data:
  configuration.yaml: ENC[AES256_GCM,data:eo1cR+1m/8HKO6u3ckz/ANC1dbOfOipnQ6ofyQWXatesWquJFQwMMr/mkVy6I6ooRTB4NgSkluFHo911TU78UN6aOCBMxSCl5EzHslasRGSzKbgdNpcixAH+fApKbnZTkzPzMfHLBVBtzE1Sodqx7MTeMJew8SPtQJ9d5dawor0cWs1VlIJmJ8bWscm/Z4Bf/tisACNJ9OzM3Uj7GOPNtVs4k2SrUCP4WsOGVZM9iinnwxSG8PJanVFZtvjxEtshJtI7xSeG3TSi1fqUOtlirC+ATcollGppBoHYZ8xW+ILHBBz9C/SYqTCQ8c55,iv:w5g0jLMvD+r0BvjzGh9OU9cNY8Pdi+GJ+ozOd+uQN7Y=,tag:ytIvjYV2B5/t8M4G2yGF9g==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVEEvN2E0NktGdXVBTEZP
        S3ZmSm9YZzdIRU9MOExGOStZaVMzaStLSHdnCm5MUk9mQm9aSGk0bUd1OGMzTVJi
        cjlXcDcxdVBWM00zSlQxYlNvaVN4TzgKLS0tIEVpcndPQXFUbjZjK2k5dzM5QXYr
        b0FaRW1pTitLVmUyeFlQSEJDNWVDRXcKOcPedb1qu4MbvvHa+bGUi2nPugOrF4XE
        A6v7C0hHhQzNfW8k3n2Ji4ifOxCbcIu46AhFRIYwtVp33M42OGzhpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T02:50:16Z"
  mac: ENC[AES256_GCM,data:DYYn/dy/2SS/OuNFGcA8hPykgpnq44EPETGn4d52eQsctyRxzeBSx8plGzWuuN7k2ia+dtCtm+4itN4QvhDQ2zQw8heZZ0mPunKCoHSI2nIXLYfmLYf8BfY9RZVzb/RvL0eznsZsjfFJkDq6TRxhQGt5DBRhLw0/Lxscuimvcuc=,iv:RBcqEA2NbWo5z1mhpNuhNDQmplBhAyF6FjKEmh0Xk9E=,tag:aiC9ZLkROs66tg8FTxVKCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
