apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-configuration
  namespace: homeassistant
data:
  configuration.yaml: ENC[AES256_GCM,data:hXxKLl4IP+c76CMLg6zaa47oQR7y1EEE8RMpMOaRZ3rp99FEeUj6WnxYfyF3JR6M/SOLSyC998fAjY+gJiRKmxhrA+MJ2lLAm0wYM9w+udQMMQGnNf94orvkstKq0zLlQ40k1REuH1RvBi5f6aQWIFvqjJHGKlnD4iTJCTftdrueS+TPUvX34MewOHbY/6BxpirbM5d56lqEhqB/Zqgeqw4pOWXXjB6LP9Tl4TxQnqp+01khoCrd5v4MkLl5m5SO+JrIgPqSQnFRPkOhQqQoNTShh/SJGrZKq80d7KXLC+aqGZkxGH34x+Zc3qaPi20=,iv:qJw2rAbL+x1JZcWdMOXQVYdOVs30vwM91IqOXaclbe4=,tag:Ewf/RFXTYDXr9bevUcsloQ==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINWRDR3BobFMwK1Z3dnFa
        dlNndVIydklET1dUQ1pUb0F5WDRUbkMrTENrCjVRVit2TnhlNU1mWWFXblZzekc0
        a09STGxGaEFJUlRNbXVnQXlGS280SFkKLS0tIFlISit5TEFrL0RVbFlYZXZNYzlt
        ZHdHL0JDWTZZMHQwZlR3MUd4UXorRFkKdZeAINLtnHtla+3LgIPaHz+mH020GvHu
        4Gj6N+9XDdC0/J8pSUqTPL57OJ2VW6RYg8ef1x7AmB8/rkI48mDREA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T01:14:04Z"
  mac: ENC[AES256_GCM,data:XIc4aN26hY4SNDc2RwdAKIKmTpAktdBB8HZRYl5B3slBHDcxppA08uczF5kHfopu62CNFKRrs/bzTVuA6e7Vray+tGnGKktE8/1zMfz3qwt+a/Is4lriFsTYKOzIGpJp9GQgUY5GJSrDHTca77JrYtFhIieogjPLHKkndgTsAlI=,iv:yHvfpEsVBRl97xYZ+jmiEYqwKP2HIEJKmKGsGiXYvU4=,tag:GoamfUfw139qnId+66i3hA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
