apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2gSa4yrUubkAIDz3tsppkavNBf8n09uRMSZ8AoaChg1D1i+Se1xdsw==,iv:lrHKwzBXKwOMZE0DuE6li1w2LE9msm9H5v3b/E/Y1XY=,tag:kTwj9sitrDgA210mCqPGcw==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNDIvei9ZcmloQWpsVHRQ
        ZWZKUk5KS2d0MnBUZllBM1ByaHBpOU01dWpFCnpWRzFydGdCM2tZQ2tETnVMOUZ5
        bzZMdERTV1dDd3R4L3NjcjQ0ajcweTQKLS0tIERKbnViL0RDR2xxOWF1UGg0Szc4
        WlVRdnNDVmpWMjV4dGozMDBoaUp2eWcKiDL6jJBlAFzAL0BrkYaEOG1IPmXd6bRD
        7JKMk/bbvEg6PNRa9+26FjtSWQBGtr8A3Il/SgSwrECA2nd6OWb3vw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T17:11:45Z"
  mac: ENC[AES256_GCM,data:ItzUfgUN64cIxd3DxpHHWW+FYzUfM9qAJTyHTD0JcwfK4UZsHT90VK/lS/vUHkxMjmBcXyin5zG62++zAiAEjjxMA3dZPIzVXQ+RLg9hoC1tNkIjo1EQtXb8+tUdK6cxaguloMlQjuad771jvPCrRYOLXvxs7Yh97D3jn46nmZU=,iv:LugHouieZlC6sMkNfpJ7UoH4AvunRn4156OHQHlCk20=,tag:06tZWnbhY1baBdSkrxRJhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
