apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZuspfxrQnpJ54g3Sizme8TMyd8cJA4QUDz+WYA2ByhGjhkem1Bo3/A==,iv:M2ev4u3TNyYvu4ptIAiN5nlRuSqLGLKQsXcghQWsBlI=,tag:uuod6t67Xn9xhRx7L7Ub5Q==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SkRLNWdiTFlkY2VqeHJ5
        TjhzVTZ0ZjNXTXJsQUxNNUw0bVRMRGJBZFhBCmdscEc5YmdETTBPYzVzbUI1eHAv
        MVhaeVF1TlFtSzVaakw4UnJmQWdvNmMKLS0tIEhuMTBkd1hsZE16bjVFdVNDdnZs
        cmE3RkVlMzRVTWVQRll6aXN2dGFOSFUKtfQnAHzUVv5pVLzQJF2DPR6AaHBO6A8C
        Ar45By1nS/N1JDw0gAEv1F9ekZOGCqr4FBCEHphIAhmZ8MvK154nmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T17:25:09Z"
  mac: ENC[AES256_GCM,data:DJMdiBGgFay/BCYmQ9AXQoaMAbZaK/8w7DVnRc8RkwxP90EbTUlkYxKFkhq4vJS/nKTFz9eeuGc5O0OQla0J4PbKGGYNkclPqYRYnAYyUCvEaAjR17BMVN9aYvDs6ErC0wMmKI/+vmAXfC0UoNA6HQSV9NVyqEGSlbhN7y5jRpA=,iv:e5seMmW/HTxrRlVAw3/71kQOfTdKZu8B1uYnjVieNOk=,tag:bWTspsSSiTDAfT12+7uLGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
