---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: glance
  name: glance
  namespace: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: glance
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glance
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: glance-env
          image: glanceapp/glance:v0.8.4
          name: glance
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config
              name: glance-config
            - mountPath: /app/assets
              name: glance-assets
            - mountPath: /etc/localtime
              name: glance-localtime
              readOnly: true
              subPath: localtime
      restartPolicy: Always
      volumes:
        - configMap:
            name: glance-config
          name: glance-config
        - configMap:
            name: glance-assets
          name: glance-assets
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: glance-localtime
          name: glance-localtime
