---
apiVersion: v1
kind: Service
metadata:
  name: glance
  namespace: glance
spec:
  ports:
    - name: glance-ui
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: glance
