apiVersion: v1
kind: Secret
metadata:
  name: mealie-config
  namespace: mealie
stringData:
  gpg-key: ENC[AES256_GCM,data:wGP1hZ5r3I+kyjW9ZRvhwPgMbJGGpGQyBLD8J2wZ/k+1pHgzkF7k/g==,iv:YdTECTLmLTIEZr01B/cAabqim328S3Xubr+VnibvcSE=,tag:t471hELHp1vzNFufryfzbw==,type:str]
  BASE_URL: ENC[AES256_GCM,data:kqHXXYf1z82cLTllUjEkNfqU1l3Mf0c=,iv:0NNA4XS7CSdhuJhoSXD3KNWIy1OgBG7QyTa2RW+IbKM=,tag:Q/Zzy88u6eKqOye5H0+bSQ==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:KXD9/ruVIOcWi0psb59V+ibo7VWb8ynha4/0mte2kHhHEFE5Rjr380bYt9E36ErKI2TgalJgVnIHZ8Nru4x7ree40gHEcLFu2osI9dUw5HSRf1xW8F4EQHIZQqRB0n2fuZRIh8/hK19QYVAVQiy0MUXNAVTZNb4NUbv8Dah8sXon4h1d9wxipCGhj0k0VDY=,iv:1pI/3i9Nw/59eCI1ruQDolvk+kyUpilZzkJJzE0t1MA=,tag:C+7aUJCQLS0oI9frRumvlg==,type:str]
  SMTP_FROM_EMAIL: ENC[AES256_GCM,data:/CFwYZw0eiPswh7tgMX3,iv:5AtTZv9E7ho/R8oHUyLiN8FbsP8ZiWb5v7SPkxZc854=,tag:7yGy6Zt+znida7NA4v+w2w==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:8uK/GPKE9SgMo8bacYGgqw==,iv:CKB5IahzRK5JvQ5K2DGVQvY/kzWeXOWPxwvh5T6bd88=,tag:1ZVEucabGjTjZIDLV/BnfA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:DIlP1ptMxJjqoXpRzhQ9gg==,iv:25nfOcW/Sdet0fF7r4S9Kffz19wnYukmRA8zB0pf5ro=,tag:0lgY+UYCA/reDinj6RarDQ==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:mbtF+Q==,iv:ynBTVnDuujJcReSvt3LKx0slaUacGS2UrbnqnnX/0uk=,tag:s1KvBK7Jvs2WtWF11yW0Xg==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:Fj41yhgf6w9QoI4Ubpsy,iv:LlhkDkmgqpPmUKsEG96XyrJ+f+Zyvp0A8hUSypxvDWQ=,tag:zaPQP6uV6D0HTLxqFSLV4A==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYy9pMUdsazdOaisvQ1dL
        TmhGMFpiWjNjSXpKdUU5aTd6RnY0VUJ3N1MwCnJHRUVSK1N4M2VIMVFoeFBjeS90
        d0xrZXNINkJpWXNVaW1mYmJDaEpJWEEKLS0tIDN3c2szVXBjdHdhOFpNMXIvZEky
        R1JsVDFGK3hsdUR1M2x3d09nRDdNK28KhG6S10S3S6PJCGVZ6CY68M2wJ/C0MzK1
        zGt1qXOzqo8Dsz/1giiVxflpn4h0c/2s1QlrD5IG9O8EE2oV4cXS+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T19:21:03Z"
  mac: ENC[AES256_GCM,data:He6AJmK7xFMAZmkpRwQrnLC2KHiUk/GDUFYCAastZQaddbr3iRDwBVAjFQZJEO4cU0neL0KdplIDh7uN4x2baY2VO13Uoor+i0/EkRqBL9F82vDqusp6SeKyOaVY1YVXcjoQLYMYBcstAPOqSUNQzX6nWyXzeeIQ7ko4/t7TFkk=,iv:2Rbi9cqGMFKF1I97ZuMr8vLz8MXbAYjDVpT8P8h2b00=,tag:uEfAdA6+eb1o4zc6cHl2Dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
