---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app device-plugin
  namespace: flux-system
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/part-of: &namespace kube-system
spec:
  dependsOn:
    - name: flux-system
      namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/namespace: *namespace
  interval: 4h
  path: ./kubernetes/apps/device-plugin/app
  prune: true
  retryInterval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
  wait: false
